services:
  postgres:
    container_name: studio-dev-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: redis
      SRH_CONNECTION_STRING: 'redis://redis:6379'

volumes:
  postgres:
    name: studio-dev-db-volume
